config/urls.py
import os
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path(os.environ.get("DJANGO_ADIN", "admin/"), admin.site.urls),    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from rooms import views as rooms_views

app_name = "core"

urlpatterns = [
    path("", rooms_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path, include
from . import views

app_name = "rooms"

"""
urlpatterns = [
    path("<int:pk>", views.detail_view, name="detail"),
]
"""

urlpatterns = [
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.UpdateRoomView.as_view(), name="update"),
    path("<int:pk>/delete/", views.delete_room, name="delete"),
    path("<int:pk>/photos/", views.EditPhotosView.as_view(), name="photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete_photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit_photo",
    ),
    path(
        "<int:pk>/photos/upload/",
        views.UploadPhotoView.as_view(),
        name="upload_photo",
    ),
    path("search/", views.search_view, name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create")
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("<int:pk>/", views.UserDetailView.as_view(), name="user"),
    path("favorite/", views.FavoriteView.as_view(), name="favorite"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:user_id>/send_verify/",
         views.send_verify_view, name="send-verify"),
    # path("login", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("verify/<str:key>/", views.complete_verification, name="verify"),
    path("login/github/", views.github_login, name="github"),
    path("login/github/callback/", views.github_callback, name="github_callback"),
    path("login/kakao/", views.kakao_login, name="kakao"),
    path("login/kakao/callback", views.kakao_callback, name="kakao_callback"),
    path("start-host/", views.switch_host, name="switch_host"),
    path("switch-language/", views.switch_language, name="switch_lang"),
]

rooms/forms.py
from django import forms
from .models import RoomType, Amenity, Facility

from django_countries.fields import CountryField


class SearchForm(forms.Form):
    city = forms.CharField(required=False, initial="Anywhere",)
    country = CountryField(blank=True).formfield()
    min_price = forms.IntegerField(required=False, initial=10)
    max_price = forms.IntegerField(required=False, initial=1000)
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=RoomType.objects.all()
    )

    guests = forms.IntegerField(required=False, initial=1)
    baths = forms.IntegerField(required=False, initial=1)
    beds = forms.IntegerField(required=False, initial=1)
    bedrooms = forms.IntegerField(required=False, initial=1)

    instant_book = forms.BooleanField(required=False, initial=False)
    superhost = forms.BooleanField(required=False, initial=False)

    amenities = forms.ModelMultipleChoiceField(
        queryset=Amenity.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=Facility.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

rooms/views.py
import math
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator, EmptyPage
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from .models import Room, RoomType, Amenity, Facility, HouseRule, Photo
from .forms import SearchForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django_countries import countries


from users import mixins as user_mixins

# third way. make list.
class HomeView(ListView):
    """ HomeView definition """

    model = Room
    paginate_by = 12
    ordering = ["created_at"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context["now"] = now
        return context


class UpdateRoomView(user_mixins.LoginOnlyView, UpdateView):
    model = Room
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "host",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )
    template_name = "rooms/room_update.html"

    def get_object(self, queryset=None):
        rooms = super().get_object(queryset=queryset)
        if rooms.host.pk == self.request.user.pk:
            return rooms

        raise Http404("Do not have access permission for this room")


class RoomDetailView(DetailView):
    """ DetailView definition """

    model = Room

    def get(self, request, *args, **kwargs):        
        request.session['room_detail_from'] = request.META.get('HTTP_REFERER')
        return super().get(request, *args, **kwargs)


class EditPhotosView(user_mixins.LoginOnlyView, DetailView):
    model = Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        rooms = super().get_object(queryset=queryset)
        if rooms.host.pk == self.request.user.pk:
            return rooms

        raise Http404("Do not have access permission for this room")


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user

    try:
        room = Room.objects.get(pk=room_pk)

        if user.pk != room.host.pk:
            messages.error(request, "While deleting photo, an error occurs.")
        else:
            room.my_photos.filter(pk=photo_pk).delete()
            messages.success(request, "Photo deleted.")

        return redirect("rooms:photos", pk=room_pk)

    except Room.DoesNotExist:
        return redirect(reverse("core:home"))

class EditPhotoView(user_mixins.LoginOnlyView, SuccessMessageMixin, UpdateView):

    model = Photo
    template_name = "rooms/photo_edit.html"
    fields = ("caption",)
    pk_url_kwarg = "photo_pk"
    success_message = "Photo edited"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse ("rooms:photos", kwargs={"pk": room_pk})

class UploadPhotoView(user_mixins.LoginOnlyView, SuccessMessageMixin, CreateView):

    model = Photo
    template_name = "rooms/photo_upload.html"    
    pk_url_kwarg = "photo_pk"
    success_message = "Photo uploaded"
    fields = ("image", "caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("pk")
        return reverse ("rooms:photos", kwargs={"pk": room_pk})

    def form_valid(self, form):
        photo = form.save(commit=False)
        pk = self.kwargs.get("pk")
        room = Room.objects.get(pk=pk)
        photo.room = room
        return super().form_valid(form)

class CreateRoomView(user_mixins.LoginOnlyView, SuccessMessageMixin, CreateView):

    model = Room
    template_name = "rooms/room_create.html"        
    success_message = "Room created"
    fields = ("name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",        
        "room_type",
        "amenities",
        "facilities",
        "house_rules",)

    def get_success_url(self):
        try:
            room_pk = Room.objects.get(pk=self.pk).pk
        except:
            return reverse("core:home")
        return reverse ("rooms:detail", kwargs={"pk": room_pk})    

    def form_valid(self, form):
        room = form.save(commit=False)        
        room.host = self.request.user
        self.pk = room.pk
        return super().form_valid(form)

@login_required
def delete_room(request, pk):
    try:                
        room = Room.objects.filter(pk=pk)        
        if request.user.pk == room.first().host.pk:
            room.delete()                    
            return redirect(reverse("users:user", kwargs={"pk": request.user.pk}))            
        else:
            message.error("You do not have authorization.")
            return redirect(reverse("core:home"))
    except Room.DoesNotExist:        
        raise Http404("Error in deleteing room. invalid room.")
    
        

"""  ---------------------------------------------------- """


def if_none_default(value, default):
    return value is not None and value or default


# class 형태로 바꾸고 싶다면.. class SearchView(View): get method를 아래 함수로 오버라이딩하면 된다.
def search_view(request):

    forms = SearchForm(request.GET)
    rooms = None
    uri = request.get_raw_uri()
    if forms.is_valid():
        city = forms.cleaned_data.get("city")
        country = forms.cleaned_data.get("country")
        min_price = forms.cleaned_data.get("min_price")
        max_price = forms.cleaned_data.get("max_price")
        room_type = forms.cleaned_data.get("room_type")
        guests = forms.cleaned_data.get("guests")
        baths = forms.cleaned_data.get("baths")
        beds = forms.cleaned_data.get("beds")
        bedrooms = forms.cleaned_data.get("bedrooms")
        instant_book = forms.cleaned_data.get("instant_book")
        superhost = forms.cleaned_data.get("superhost")
        amenities = forms.cleaned_data.get("amenities")
        facilities = forms.cleaned_data.get("facilities")

        filtering = {}

        # city filtering
        if city != "Anywhere":
            filtering["city__startswith"] = city

        if country:
            filtering["country"] = country

        # filter with price
        if min_price is not None and max_price is not None:
            filtering["price__gte"] = min_price
            filtering["price__lte"] = max_price

        # room type filtering
        if room_type is not None:
            filtering["room_type"] = room_type

        # guests, beds, bedrooms, baths filtering
        if guests is not None:
            filtering["guests__gte"] = guests
        if beds is not None:
            filtering["beds__gte"] = beds
        if bedrooms is not None:
            filtering["bedrooms__gte"] = bedrooms
        if baths is not None:
            filtering["baths__gte"] = baths
        # instant book filtering
        if instant_book is not None:
            filtering["instant_book"] = instant_book
        # superhost filtering
        if superhost is not None:
            filtering["host__is_superhost"] = superhost

        print(filtering)
        mtom_filter = Room.objects.filter()

        for c in amenities:
            mtom_filter = mtom_filter.filter(amenities=c)

        for c in facilities:
            mtom_filter = mtom_filter.filter(facilities=c)

        qs = mtom_filter.filter(**filtering).order_by("created_at")
        paginator = Paginator(qs, 10, allow_empty_first_page=True)
        page = int(request.GET.get("page", 1))
        rooms = paginator.page(page)
        print(filtering)
        print(rooms)
    else:
        forms = SearchForm()

    return render(
        request,
        "rooms/search.html",
        context={"forms": forms, "rooms": rooms, "uri": uri},
    )


# django form을 이용해야 하기 때문에.. 얘는 빠이빠이..
"""def search_view(request):
    city = request.GET.get("city", "anywhere")
    city = city == "" and "anywhere" or city
    country = request.GET.get("country", "AnyCountry")

    room_type = request.GET.get("room_type", 0)
    room_type = int(room_type)

    min_price = request.GET.get("min_price")
    min_price = min_price and int(min_price) or 10

    max_price = request.GET.get("max_price")
    max_price = max_price and int(max_price) or 100

    guests = request.GET.get("guests")
    guests = guests and int(guests) or 1

    beds = request.GET.get("beds")
    beds = beds and int(beds) or 1

    baths = request.GET.get("baths")
    baths = baths and int(baths) or 1

    bedrooms = request.GET.get("bedrooms")
    bedrooms = bedrooms and int(bedrooms) or 1

    checked_amenities = request.GET.getlist("amenities")
    checked_facilities = request.GET.getlist("facilities")

    is_instant = bool(request.GET.get("instant", False))
    is_superhost = bool(request.GET.get("superhost", False))

    room_types = RoomType.objects.all()
    amenities = Amenity.objects.all()
    facilities = Facility.objects.all()
    house_rules = HouseRule.objects.all()

    filtering = {}

    # city filtering
    if city != "anywhere":
        filtering["city__startswith"] = city

    if country != "AnyCountry":
        filtering["country"] = country

    # filter with price
    filtering["price__gte"] = min_price
    filtering["price__lte"] = max_price

    # room type filtering
    if room_type != 0:
        filtering["room_type_id"] = room_type

    # guests, beds, bedrooms, baths filtering
    if guests != 0:
        filtering["guests__gte"] = guests
    if beds != 0:

templates/partials/avatar.html
<!-- use below div tag because of size -->
<div class="w-full h-full bg-gray-300 rounded-full flex justify-center items-center bg-cover bg-center bg-no-repeat"
    {% if profile.avatar %} style="background-image: url('{{profile.avatar.url}}')">{% else %}>
    <span
        class="text-3xl text-gray-500">{% filter capfirst|first %}{{profile.first_name}}{% endfilter %}</span>{% endif %}
</div>

templates/partials/footer.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<footer class="border-t w-full h-auto mt-10">
    <div class="flex flex-col w-full h-full justify-center items-center mx-auto">
        <span class="text-gray-600 font-semibold">&copy; DjangoBnB</span>
        <span class="text-gray-600 font-semibold">{% trans "please don't copy us" %}</span>
    </div>
    <div class="mx-auto w-1/2 flex content-center my-5">
        <select id="lang-select" class="mx-auto w-1/5" style="outline: 1px gray solid;">
            <option value="en" 
            {% if LANGUAGE_CODE == 'en' %}
                selected
            {% endif %}
                >English</option>
            <option value="es" {% if LANGUAGE_CODE == 'es' %}
            selected
        {% endif %}>Spanish</option>
            <option value="ko" {% if LANGUAGE_CODE == 'ko' %}
            selected
        {% endif %}>Korean</option>
        </select>
    </div>
</footer>

templates/partials/form_auth.html
<form class="w-full" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-auth {% if field.errors %}input-error{% endif %}">
        <!--{{field.label}}-->
        {{field}}
        {% include 'partials/input_errors.html' with errors=field.errors %}
    </div>
    {% endfor %}
    <div class="form-auth">
        {% include "partials/input_errors.html" with errors=form.non_field_errors %}
    </div>
    <div class="auth-btn mb-2 bg-red-500 text-white hover:bg-red-400 transition duration-200">
        <button class="w-full h-full mx-auto">{{cta}}</button>
    </div>
</form>

templates/partials/form_auth_label.html
<form class="w-full" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-auth {% if field.errors %}input-error{% endif %}">
        {{field.label}}
        {{field}}
        {% include 'partials/input_errors.html' with errors=field.errors %}
    </div>
    {% endfor %}
    <div class="form-auth">
        {% include "partials/input_errors.html" with errors=form.non_field_errors %}
    </div>
    <div class="auth-btn mb-2 bg-red-500 text-white hover:bg-red-400 transition duration-200">
        <button class="w-full h-full mx-auto">{{cta}}</button>
    </div>
</form>

templates/partials/header.html
<header>
    <a href="{% url "core:home" %}"><p>home</p></a>
    <ul>
        <li><a href="#">login</a></li>
    </ul>
</header>

templates/partials/input_errors.html
{% if errors %}
    {% for e in errors %}
        <span class="error-message">{{e}}</span>
    {% endfor %}
{% endif %}

templates/partials/messages.html
{% if messages %}
<ul class="absolute mx-auto left-0 right-0 flex justify-center message fade-out">
    {% for message in messages %}
    <li class="font-medium rounded-full px-3 py-2 message {% if message.tags %}{{message.tags}}{% endif %} fade-out">
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
    <ul class="flex justify-end items-center text-sm font-medium w-full h-full">
        {% if user.is_authenticated %}
            <li class="nav-link"><a href="{% url "users:switch_host" %}">
            {% if request.session.is_host %}
            As host
            {% else %}
            As guest
            {% endif %}
            </a></li>
            {% if request.session.is_host %}
            <li class="nav-link"><a href="{% url "rooms:create" %}">Create Room</a>
            {% endif %}
            <li class="nav-link">
                <a href="{% url "users:favorite" %}" class="flex items-center">
                    Favorite
                </a>
            </li>
            <li class="nav-link">
                <a href="{% url "users:user" pk=user.pk %}" class="flex items-center">
                    <div class="w-10 h-10 mr-2 border rounded-full border-gray-700">{% include "partials/avatar.html" with profile=user %}</div>
                    {{user.username}}
                </a>
            </li>    
            <li class="nav-link"><a href="{% url "users:logout" %}">logout</a></li>
        {% else %}
            <li class="nav-link"><a href="{% url "users:login" %}">login</a></li>
            <li class="nav-link"><a href="{% url "users:signup" %}">signup</a></li>
        {% endif %}
    </ul>

templates/partials/room.html
<a href="{% url "rooms:detail" room.pk %}">
    <div class="flex flex-col justify-center">
        <div class="mb-3 bg-center bg-cover w-full h-64 rounded-lg" {% if room.first_image is not None %}style="background-image: url({{room.first_image}})"{% endif %}></div>
        <div class="flex justify-between  px-1">
            <div class="flex items-center w-4/5">
                {% if  room.host.is_superhost %}
                <span class="text-gray-800 font-bold text-xs border border-gray-800 rounded-md px-1 mr-1">SUPERHOST</span>
                {% endif %}
                <span class="text-gray-600 text-xs truncate pr-1">{{room.city}}·{{room.country.name}}</span>
            </div>
            <div class="flex w-1/5 justify-end items-center">
                <i class="fas fa-star text-red-600 font-bold text-xs mr-2"></i>
                <span class="text-gray-900 text-xs">{{room.get_ratings}}</span>
            </div>
        </div>
        <div class="h-6 w-11/12 mb-2 truncate">
            <span class="text-gray-600 text-base font-thin">{{room.name}}</p>
        </div>
        <div>
            <span class="text-gray-900 font-extrabold">${{room.price}}</span><span class="text-gray-600 font-thin"> / night</span>
        </div>
    </div>
</a>

templates/partials/social_login.html
<div class="w-full ">
  <a href="{% url 'users:github' %}">
  <div class="auth-btn bg-gray-900 text-white ">
    <div class="flex justify-center w-1/5">
      <i class="fab fa-github fa-2x"></i>
    </div>
    <div class="ml-10 flex justify-start w-4/5">  
      Continue with Github
    </div>
  </div>
  </a>
  <a href="{% url 'users:kakao' %}">
  <div class="auth-btn bg-yellow-400 text-yellow-900">
    <div class="flex justify-center w-1/5">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 208 191.94"><g><polygon class="text-yellow-900" points="76.01 89.49 87.99 89.49 87.99 89.49 82 72.47 76.01 89.49"/><path class="cls-1" d="M104,0C46.56,0,0,36.71,0,82c0,29.28,19.47,55,48.75,69.48-1.59,5.49-10.24,35.34-10.58,37.69,0,0-.21,1.76.93,2.43a3.14,3.14,0,0,0,2.48.15c3.28-.46,38-24.81,44-29A131.56,131.56,0,0,0,104,164c57.44,0,104-36.71,104-82S161.44,0,104,0ZM52.53,69.27c-.13,11.6.1,23.8-.09,35.22-.06,3.65-2.16,4.74-5,5.78a1.88,1.88,0,0,1-1,.07c-3.25-.64-5.84-1.8-5.92-5.84-.23-11.41.07-23.63-.09-35.23-2.75-.11-6.67.11-9.22,0-3.54-.23-6-2.48-5.85-5.83s1.94-5.76,5.91-5.82c9.38-.14,21-.14,30.38,0,4,.06,5.78,2.48,5.9,5.82s-2.3,5.6-5.83,5.83C59.2,69.38,55.29,69.16,52.53,69.27Zm50.4,40.45a9.24,9.24,0,0,1-3.82.83c-2.5,0-4.41-1-5-2.65l-3-7.78H72.85l-3,7.78c-.58,1.63-2.49,2.65-5,2.65a9.16,9.16,0,0,1-3.81-.83c-1.66-.76-3.25-2.86-1.43-8.52L74,63.42a9,9,0,0,1,8-5.92,9.07,9.07,0,0,1,8,5.93l14.34,37.76C106.17,106.86,104.58,109,102.93,109.72Zm30.32,0H114a5.64,5.64,0,0,1-5.75-5.5V63.5a6.13,6.13,0,0,1,12.25,0V98.75h12.75a5.51,5.51,0,1,1,0,11Zm47-4.52A6,6,0,0,1,169.49,108L155.42,89.37l-2.08,2.08v13.09a6,6,0,0,1-12,0v-41a6,6,0,0,1,12,0V76.4l16.74-16.74a4.64,4.64,0,0,1,3.33-1.34,6.08,6.08,0,0,1,5.9,5.58A4.7,4.7,0,0,1,178,67.55L164.3,81.22l14.77,19.57A6,6,0,0,1,180.22,105.23Z"/></g></svg>
      <i class="fas fa-comment fa-2x"></i>
    </div>
    <div class="ml-10 flex justify-start w-4/5">
      Continue with Kakao
    </div>
  </div>
  </a>
</div>
<div class="flex justify-center items-center w-full my-5">
    <div class="h-px w-full bg-gray-500"></div>
    <span class="text-gray-700 font-medium mx-2">or</span>
    <div class="h-px w-full bg-gray-500"></div>
</div>