config/urls.py
import os
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path(os.environ.get("DJANGO_ADIN", "admin/"), admin.site.urls),    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from rooms import views as rooms_views

app_name = "core"

urlpatterns = [
    path("", rooms_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_list, name="toggle"),
]

rooms/urls.py
from django.urls import path, include
from . import views

app_name = "rooms"

"""
urlpatterns = [
    path("<int:pk>", views.detail_view, name="detail"),
]
"""

urlpatterns = [
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.UpdateRoomView.as_view(), name="update"),
    path("<int:pk>/delete/", views.delete_room, name="delete"),
    path("<int:pk>/photos/", views.EditPhotosView.as_view(), name="photos"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete_photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit_photo",
    ),
    path(
        "<int:pk>/photos/upload/",
        views.UploadPhotoView.as_view(),
        name="upload_photo",
    ),
    path("search/", views.search_view, name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create")
]

rooms/forms.py
from django import forms
from .models import RoomType, Amenity, Facility

from django_countries.fields import CountryField


class SearchForm(forms.Form):
    city = forms.CharField(required=False, initial="Anywhere",)
    country = CountryField(blank=True).formfield()
    min_price = forms.IntegerField(required=False, initial=10)
    max_price = forms.IntegerField(required=False, initial=1000)
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=RoomType.objects.all()
    )

    guests = forms.IntegerField(required=False, initial=1)
    baths = forms.IntegerField(required=False, initial=1)
    beds = forms.IntegerField(required=False, initial=1)
    bedrooms = forms.IntegerField(required=False, initial=1)

    instant_book = forms.BooleanField(required=False, initial=False)
    superhost = forms.BooleanField(required=False, initial=False)

    amenities = forms.ModelMultipleChoiceField(
        queryset=Amenity.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=Facility.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple,
    )

rooms/views.py
import math
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator, EmptyPage
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from .models import Room, RoomType, Amenity, Facility, HouseRule, Photo
from .forms import SearchForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django_countries import countries


from users import mixins as user_mixins

# third way. make list.
class HomeView(ListView):
    """ HomeView definition """

    model = Room
    paginate_by = 12
    ordering = ["created_at"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context["now"] = now
        return context


class UpdateRoomView(user_mixins.LoginOnlyView, UpdateView):
    model = Room
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "host",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )
    template_name = "rooms/room_update.html"

    def get_object(self, queryset=None):
        rooms = super().get_object(queryset=queryset)
        if rooms.host.pk == self.request.user.pk:
            return rooms

        raise Http404("Do not have access permission for this room")


class RoomDetailView(DetailView):
    """ DetailView definition """

    model = Room

    def get(self, request, *args, **kwargs):        
        request.session['room_detail_from'] = request.META.get('HTTP_REFERER')
        return super().get(request, *args, **kwargs)


class EditPhotosView(user_mixins.LoginOnlyView, DetailView):
    model = Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        rooms = super().get_object(queryset=queryset)
        if rooms.host.pk == self.request.user.pk:
            return rooms

        raise Http404("Do not have access permission for this room")


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user

    try:
        room = Room.objects.get(pk=room_pk)

        if user.pk != room.host.pk:
            messages.error(request, "While deleting photo, an error occurs.")
        else:
            room.my_photos.filter(pk=photo_pk).delete()
            messages.success(request, "Photo deleted.")

        return redirect("rooms:photos", pk=room_pk)

    except Room.DoesNotExist:
        return redirect(reverse("core:home"))

class EditPhotoView(user_mixins.LoginOnlyView, SuccessMessageMixin, UpdateView):

    model = Photo
    template_name = "rooms/photo_edit.html"
    fields = ("caption",)
    pk_url_kwarg = "photo_pk"
    success_message = "Photo edited"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse ("rooms:photos", kwargs={"pk": room_pk})

class UploadPhotoView(user_mixins.LoginOnlyView, SuccessMessageMixin, CreateView):

    model = Photo
    template_name = "rooms/photo_upload.html"    
    pk_url_kwarg = "photo_pk"
    success_message = "Photo uploaded"
    fields = ("image", "caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("pk")
        return reverse ("rooms:photos", kwargs={"pk": room_pk})

    def form_valid(self, form):
        photo = form.save(commit=False)
        pk = self.kwargs.get("pk")
        room = Room.objects.get(pk=pk)
        photo.room = room
        return super().form_valid(form)

class CreateRoomView(user_mixins.LoginOnlyView, SuccessMessageMixin, CreateView):

    model = Room
    template_name = "rooms/room_create.html"        
    success_message = "Room created"
    fields = ("name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",        
        "room_type",
        "amenities",
        "facilities",
        "house_rules",)

    def get_success_url(self):
        try:
            room_pk = Room.objects.get(pk=self.pk).pk
        except:
            return reverse("core:home")
        return reverse ("rooms:detail", kwargs={"pk": room_pk})    

    def form_valid(self, form):
        room = form.save(commit=False)        
        room.host = self.request.user
        self.pk = room.pk
        return super().form_valid(form)

@login_required
def delete_room(request, pk):
    try:                
        room = Room.objects.filter(pk=pk)        
        if request.user.pk == room.first().host.pk:
            room.delete()                    
            return redirect(reverse("users:user", kwargs={"pk": request.user.pk}))            
        else:
            message.error("You do not have authorization.")
            return redirect(reverse("core:home"))
    except Room.DoesNotExist:        
        raise Http404("Error in deleteing room. invalid room.")
    
        

"""  ---------------------------------------------------- """


def if_none_default(value, default):
    return value is not None and value or default


# class 형태로 바꾸고 싶다면.. class SearchView(View): get method를 아래 함수로 오버라이딩하면 된다.
def search_view(request):

    forms = SearchForm(request.GET)
    rooms = None
    uri = request.get_raw_uri()
    if forms.is_valid():
        city = forms.cleaned_data.get("city")
        country = forms.cleaned_data.get("country")
        min_price = forms.cleaned_data.get("min_price")
        max_price = forms.cleaned_data.get("max_price")
        room_type = forms.cleaned_data.get("room_type")
        guests = forms.cleaned_data.get("guests")
        baths = forms.cleaned_data.get("baths")
        beds = forms.cleaned_data.get("beds")
        bedrooms = forms.cleaned_data.get("bedrooms")
        instant_book = forms.cleaned_data.get("instant_book")
        superhost = forms.cleaned_data.get("superhost")
        amenities = forms.cleaned_data.get("amenities")
        facilities = forms.cleaned_data.get("facilities")

        filtering = {}

        # city filtering
        if city != "Anywhere":
            filtering["city__startswith"] = city

        if country:
            filtering["country"] = country

        # filter with price
        if min_price is not None and max_price is not None:
            filtering["price__gte"] = min_price
            filtering["price__lte"] = max_price

        # room type filtering
        if room_type is not None:
            filtering["room_type"] = room_type

        # guests, beds, bedrooms, baths filtering
        if guests is not None:
            filtering["guests__gte"] = guests
        if beds is not None:
            filtering["beds__gte"] = beds
        if bedrooms is not None:
            filtering["bedrooms__gte"] = bedrooms
        if baths is not None:
            filtering["baths__gte"] = baths
        # instant book filtering
        if instant_book is not None:
            filtering["instant_book"] = instant_book
        # superhost filtering
        if superhost is not None:
            filtering["host__is_superhost"] = superhost

        print(filtering)
        mtom_filter = Room.objects.filter()

        for c in amenities:
            mtom_filter = mtom_filter.filter(amenities=c)

        for c in facilities:
            mtom_filter = mtom_filter.filter(facilities=c)

        qs = mtom_filter.filter(**filtering).order_by("created_at")
        paginator = Paginator(qs, 10, allow_empty_first_page=True)
        page = int(request.GET.get("page", 1))
        rooms = paginator.page(page)
        print(filtering)
        print(rooms)
    else:
        forms = SearchForm()

    return render(
        request,
        "rooms/search.html",
        context={"forms": forms, "rooms": rooms, "uri": uri},
    )


# django form을 이용해야 하기 때문에.. 얘는 빠이빠이..
"""def search_view(request):
    city = request.GET.get("city", "anywhere")
    city = city == "" and "anywhere" or city
    country = request.GET.get("country", "AnyCountry")

    room_type = request.GET.get("room_type", 0)
    room_type = int(room_type)

    min_price = request.GET.get("min_price")
    min_price = min_price and int(min_price) or 10

    max_price = request.GET.get("max_price")
    max_price = max_price and int(max_price) or 100

    guests = request.GET.get("guests")
    guests = guests and int(guests) or 1

    beds = request.GET.get("beds")
    beds = beds and int(beds) or 1

    baths = request.GET.get("baths")
    baths = baths and int(baths) or 1

    bedrooms = request.GET.get("bedrooms")
    bedrooms = bedrooms and int(bedrooms) or 1

    checked_amenities = request.GET.getlist("amenities")
    checked_facilities = request.GET.getlist("facilities")

    is_instant = bool(request.GET.get("instant", False))
    is_superhost = bool(request.GET.get("superhost", False))

    room_types = RoomType.objects.all()
    amenities = Amenity.objects.all()
    facilities = Facility.objects.all()
    house_rules = HouseRule.objects.all()

    filtering = {}

    # city filtering
    if city != "anywhere":
        filtering["city__startswith"] = city

    if country != "AnyCountry":
        filtering["country"] = country

    # filter with price
    filtering["price__gte"] = min_price
    filtering["price__lte"] = max_price

    # room type filtering
    if room_type != 0:
        filtering["room_type_id"] = room_type

    # guests, beds, bedrooms, baths filtering
    if guests != 0:
        filtering["guests__gte"] = guests
    if beds != 0:

templates/rooms/detail.html
{% extends "base.html" %} 
{% block pagename %} Home {% endblock pagename %}
{%block content %}
<div>
    <h2>{{room.name}}</h2>
    <h4>{{room.description}}</h4>
</div>
<div>
    <h2>By: <a href={{room.host.get_absolute_url}}>{{room.host}}</a> {% if room.host.is_superhost %}&lt;&lt;Super host&gt;&gt;{% else %}&lt;&lt;Not a Super host&gt;&gt;{% endif %}</h2>
    <h3>Amenities</h3>
    <h4>Room type: {{room.room_type}}</h4>
    {% for p in room.my_photos.all %}
        <img src="{{p.image.url}}" width="100px" height="100px" />
    {% endfor %}
    <ul>
    {% for a in room.amenities.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
    {% for a in room.facilities.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
    <h3>House rules</h3>
    <ul>
    {% for a in room.house_rules.all %}
        <li>{{a}}</li>
    {% endfor %}
    </ul>
</div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends 'base.html' %}
{% block pagename %}
Edit Photo
{% endblock pagename %}

{% block content %}
<div class="xl:w-2/5 lg:w-2/5 md:w-40 sm:flex-shrink-0 border p-10 min-w-1/2 h-75vh overflow-y-auto">
    {% include "partials/form_auth_label.html" with form=form cta="Update Photo" %}
    
</div>

{% endblock content %}

templates/rooms/photo_upload.html
{% extends 'base.html' %}
{% block pagename %}
Upload Photo
{% endblock pagename %}

{% block content %}
<div class="xl:w-2/5 lg:w-2/5 md:w-40 sm:flex-shrink-0 border p-10 min-w-1/2 h-75vh overflow-y-auto">
    {% include "partials/form_auth_label.html" with form=form cta="Update Photo" %}
    
</div>

{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %} 
{% load countries %}
{% load is_booked i18n %}
{% load is_in_fav %}
{% get_countries as countries %}

{% block pagename %} Home {% endblock pagename %}
{%block content %}
<div class="w-5/6 max-w-full h-auto flex flex-col">
    <div class="w-5/6 flex flex-col h-20vh mb-10">
        <h2 class="text-2xl">{{object.name}}</h2>
        <div class="w-full flex items-baseline text-base">
            <i class="fas fa-star text-red-500 font-bold text-base ml-3 mr-2"></i>
            <span>{{object.get_ratings}}</span>
            <span class="text-base text-gray-700">({{object.my_reviews.count}})</span>
            {% if object.host.is_superhost %}
            <span class="mx-2 text-gray-700 text-base">﹒ <i class="fas fa-check text-red-500 mr-1"></i>SUPERHOST</span>
            {% endif %}
            <span class="mx-1 text-gray-700 text-base">﹒ {{object.city}}, {{object.country.name}}</span>
        </div>
    </div>
    <div class="w-full flex flex-row h-50vh mb-10 mx-auto">
        <div class="w-3/5 h-full bg-gray-100 mr-5 bg-cover bg-center rounded-l-lg" {% if object.first_image is not None %}style="background-image: url('{{object.first_image}}');"{% endif %}></div>
        <div class="w-2/5 h-full bg-gray-100 grid-cols-2 grid grid-rows-2 gap-5">
            {% for image in object.from_second_four_image %}
            <div class="w-full h-full bg-cover bg-center {% if forloop.counter is 2 %}rounded-tr-lg{% elif forloop.counter is 4 %}rounded-br-lg{% endif %}" style="background-image: url('{{image.image.url}}');">
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="w-full h-auto mx-auto flex justify-around">
        <div class="w-1/2 h-auto">
            <div class="flex justify-between items-center mb-8">
                <div class="block">
                    <p class="text-gray-800 text-base">{{ object.name }}</p>
                    <p class="text-base font-thin text-gray-500">{{ object.city }}</p>
                </div>
                <div class="w-12 h-12">
                    {% include "partials/avatar.html" with profile=object.host %}
                    <p class="text-gray-600 font-light text-center text-xs">{{ object.host.first_name }}</p>
                </div>
            </div>

            {% if user.is_authenticated %}
                {% is_in_fav room.pk as is_in_fav_boolean %}                
                {% if is_in_fav_boolean %}
                    <a href="{% url 'lists:toggle' room.pk %}?action=remove" class="btn w-1/2 text-gray-700 bg-red-300 hover:bg-red-500 transition duration-150 mb-4">{% trans "Remove favorite list" %}</a>
                {% else %}
                    <a href="{% url 'lists:toggle' room.pk %}?action=add" class="btn w-1/2 text-gray-700 bg-yellow-300 hover:bg-yellow-500 transition duration-150 mb-4">{% trans "Add favorite list" %}</a>
                {% endif %}
            {% endif %}
                
            <hr class="mb-4">
            <div class="felx">
                <span class="mr-5 text-gray-700 font-normal text-base">{{ room.room_type }}</span>
                <span class="mr-5 text-gray-700 font-normal text-base">max guest{{ room.guests|pluralize }} {{ room.guests }}</span>
                <span class="mr-5 text-gray-700 font-normal text-base">bed{{ room.beds|pluralize }} {{ room.beds }}</span>
                <span class="mr-5 text-gray-700 font-normal text-base">bedroom{{ room.bedrooms|pluralize }} {{ room.bedrooms }}</span>
                <span class="mr-5 text-gray-700 font-normal text-base">bath{{ room.baths|pluralize }} {{ room.baths }}</span>
            </div>
            <div class="border-t border-gray-400 mt-5 pt-5">
                <p class="text-gray-600 text-base">{{ room.description }}</p>
            </div>
            <div class="border-t border-gray-400 mt-5 pt-5">
                <h2 class="text-xl text-gray-600">
                    Amenities</h2>
                    <div class="grid grid-cols-2 w-full h-auto">
                        {% for a in room.amenities.all %}
                            <p class="text-base font-normal text-gray-500">{{ a }}</p>
                        {% endfor %}
                    </div>
            </div>
            <div class="border-t border-gray-400 mt-5 pt-5">
                <h2 class="text-xl text-gray-600">
                    Facilities</h2>
                    <div class="grid grid-cols-2 w-full h-auto">
                        {% for a in room.facilities.all %}
                            <p class="text-base font-normal text-gray-500">{{ a }}</p>
                        {% endfor %}
                    </div>
            </div>
            <div class="border-t border-gray-400 mt-5 pt-5">
                <h2 class="text-xl text-gray-600">
                    House rules</h2>
                    <div class="grid grid-cols-2 w-full h-auto">
                        {% for a in room.house_rules.all %}
                            <p class="text-base font-normal text-gray-500">{{ a }}</p>
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if user == object.host %}
            <a href="{% url 'rooms:update' pk=object.pk %}">
                <div class="btn w-full bg-green-500 text-white hover:bg-green-700 transition duration-150 mb-2">
                    Update Room
                </div>
            </a>
            <a href="{% url 'rooms:delete' pk=object.pk %}">
                <div class="btn w-full bg-red-500 text-white hover:bg-red-700 transition duration-150">
                    Delete Room
                </div>
            </a>
            {% else %}                
                {% if not user.session.is_host %}
                    {% for month in room.get_this_and_next_months %}
                        <div class="w-full h-auto border border-gray-400 my-4 p-2">
                            <div class="mx-auto text-center my-2"><p class="text-lg text-gray-700">{{ month.get_month }} - {{ month.year }}</p></div>
                            <div class="w-full h-auto grid grid-cols-7 text-center my-2 gap-1">
                                {% for week_day in month.day_names %}
                                    <p class="{% if week_day == 'Sun' %}text-red-500{% elif week_day == 'Sat' %}text-blue-500{% endif %}">{{ week_day }}</p>
                                {% endfor %}
                                {% for day in month.get_days %}
                                    {% is_booked room day as is_booked_bool %}
                                    {% if day.day != 0 %}
                                        {% if day.past %}
                                        <p class="p-1 p-1 bg-gray-200 text-gray-300">{{ day.day }}</p>
                                        {% elif is_booked_bool %}
                                        <p class="p-1 p-1 bg-gray-200 text-gray-400 line-through">{{ day.day }}</p>
                                        {% else %}
                                        <a href="{% url 'reservations:create' room.pk day.year day.month day.day %}" >
                                            <p class="p-1 bg-gray-200 hover:bg-gray-500 hover:text-white duration-150 transition rounded cursor-pointer">{{ day.day }}</p>
                                        </a>
                                        {% endif %}
                                    {% else %}
                                        <p></p>
                                    {% endif %}
                                        
                                {% endfor %}
                            </div>
                            
                        </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>

    </div>
    <div class="border-t border-gray-400 mt-5 pt-5 w-full h-auto">
        <h2 class="text-xl text-gray-600">
        <i class="fas fa-star text-red-500 font-bold text-base ml-3 mr-2"></i>{{ object.get_ratings}} points ({{ room.my_reviews.count }} review{{room.my_reviews.count|pluralize}})</h2>
        <div class="grid grid-cols-2 w-full h-auto">
            {% for i, v in object.sum_reviews.items %}
            <div class="flex flex-row justify-center w-full h-auto my-auto">
                <div class="grid grid-cols-2 items-center justify-center w-full h-auto pl-3">
                    <p class="ml-2 w-full text-lg text-gray-700 font-light">{{ i }}: {{ v.0 }}</p>
                    <div class="relative px-2 flex items-center w-full">
                        <div class="overflow-hidden h-2 w-full text-xs flex rounded bg-pink-200">
                            <div style="width:{{ v.1 }}%" class="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-pink-500"></div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="border-t border-gray-400 mt-5 pt-5 w-full h-auto flex justify-center">
        <div class="w-11/12 h-auto grid grid-cols-2 justify-center">
        {% for r in object.my_reviews.all %}
            <div class="h-auto w-full flex flex-col mb-12 px-4">
                <div class="w-full h-auto flex flex-row mb-2">
                    <div class="w-16 h-16">
                    {% include "partials/avatar.html" with profile=r.user %}
                    </div>
                    <div class="pl-4 w-auto h-auto flex flex-col">
                        <p>{{ r.user.first_name }}</p>
                        <p>{{ r.created_at|date:"Y, M" }}</p>
                    </div>
                </div>
                <div class="w-full h-auto flex flex-row">
                    <p class="font-light text-base text-gray-700">{{ r.review }}</p>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

templates/rooms/room_photos.html
{% extends 'base.html' %}
{% block pagename %}
{{room.host}}'s photos
{% endblock pagename %}

{% block content %}

<a href="{% url 'rooms:upload_photo' room.pk %}" class="w-1/4 text-center " style="justify-self: start;">
    <div class="btn bg-blue-500 hover:bg-blue-700 text-white transition duration-150">
        Upload photo
    </div>
</a>

<div class="container p-5 min-w-1/2 h-75vh overflow-y-auto">
    {% for p in room.my_photos.all %}
        <div class="mb-5 w-full p-5 border flex justify-between">
            <div class="flex items-start">
                <img src={{p.image.url}} class="w-32 h-32 mr-5" />
                <span>{{p.caption}}</span>
            </div>
            <div class="flex flex-col w-auto">
                <a class="btn bg-green-400 w-20 mb-2 text-green-700 hover:bg-green-600 hover:text-white transition duration-150" href="{% url 'rooms:edit_photo' room_pk=room.pk photo_pk=p.pk %}">Edit</a>
                <a class="btn bg-red-400 w-20 text-red-700 hover:bg-red-600 hover:text-white transition duration-150" href="{% url 'rooms:delete_photo' room_pk=room.pk photo_pk=p.pk %}">Delete</a>
            </div>
        </div>
    {% endfor %}

    <div class="flex justify-center">
        <a class="text-teal-500 font-2xl font-medium hover:underline" href="{% url 'rooms:update' pk=room.pk %}">Back to room</a>
    </div>
</div>

{% endblock content %}

templates/rooms/search copy.html
{% extends "base.html" %}
{% block pagename %}
Seaeerch
{% endblock pagename %}
{% block search_bar %}
    {{s_country}}
    <form method="get" action="{% url "rooms:search" %}">
    <div>
        <label for="city">City</label>
        <input value={{city}} name="city" id="city" placeholder="Search by city" />
    </div>
    <div>
        <label for="country">Country</label>
        <select id="country" name="country">
            <option value="AnyCountry" {% if country is "AnyCountry" %}selected{% endif %}>Any country</option>
            
            {% for c in countries %}            
            <option value="{{c.code}}" {% if c.code == s_country %}selected{% endif %}>
            {{c.name}}
            </option>
            {% endfor %}
        </select>
    </div>
    <div>
        <label for="room_type">Room type</label>
        <select id="room_type" name="room_type">
            <option value="0" {% if s_room_type is 0 %}selected{% endif %}>Any kind</option>
            {% for c in room_types %}
            <option value="{{c.pk}}" {% if c.pk is s_room_type %}selected{% endif %}>
            {{c.name}}
            </option>
            {% endfor %}
        </select>
    </div>
    <div>
        <p>Price</p>
        <label for="min_price">Min. pirce</label>
        <input value={{min_price}} name="min_price" id="min_price"  />
        <label for="max_price">Max. pirce</label>
        <input value={{max_price}} name="max_price" id="max_price" />
    </div>
    <div>
        <label for="guests">Guests</label>
        <input value={{guests}} name="guests" id="guests" placeholder="How many guest?" />
    </div>
    <div>
        <label for="beds">Beds</label>
        <input value={{beds}} name="beds" id="beds" placeholder="How many beds?" />
    </div>
    <div>
        <label for="bedrooms">Bedrooms</label>
        <input value={{bedrooms}} name="bedrooms" id="bedrooms" placeholder="How many beds?" />
    </div>
    <div>
        <label for="baths">Baths</label>
        <input value={{baths}} name="baths" id="baths" placeholder="How many baths?" />
    </div>
    <div>
        <label for="instant">Do you want instant only?</label>
        <input type="checkbox" name="instant" id="instant" value="{{is_instant}}" {% if is_instant %}checked{% endif %} />
        <label for="superhost">Do you want superhost?</label>
        <input type="checkbox" name="superhost" id="superhost" value="{{is_superhost}}" {% if is_superhost %}checked{% endif %}/>
    </div>
    <div>
        <h3>Amenities</h3>
        <ul>
        {% for a in amenities %}
            <li><input type="checkbox" name="amenities" id="a_{{a.pk}}" value="{{a.pk}}" {% if a.pk|slugify in checked_amenities %}checked{% endif %} /><label for="a_{{a.pk}}">{{a.name}}</li>
        {% endfor %}
        </ul>
    </div>
    <div>
        <h3>Facilities</h3>
        <ul>
        {% for f in facilities %}
            <li><input type="checkbox" name="facilities" id="f_{{f.pk}}" value="{{f.pk}}" {% if f.pk|slugify in checked_facilities %}checked{% endif %} /><label for="f_{{f.pk}}">{{f.name}}</li>
        {% endfor %}
        </ul>
    </div>
    <button>Search</button>
    <div>
        <h1>{{rooms.count}} found</h1>
        {% for r in rooms %}
        <a href="/rooms/{{r.pk}}"><p>{{r.name}}</p></a>
        {% endfor %}
    </div>
{% endblock search_bar %}
{% block content %}
You are searching city {{city}}, right?
{% endblock content %}