config/urls.py
import os
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path(os.environ.get("DJANGO_ADIN", "admin/"), admin.site.urls),    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:host_pk>/<int:guest_pk>/", views.go_conversation,name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view() ,name="detail"),
]

core/urls.py
from django.urls import path

from rooms import views as rooms_views

app_name = "core"

urlpatterns = [
    path("", rooms_views.HomeView.as_view(), name="home"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>",
        views.create,
        name="create",
    ),
    path("<int:pk>", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
]

reservations/models.py
import datetime

from django.db import models
from django.db.models import Q
from core.models import AbstractTimeStamped
from django.utils import timezone


class BookedDay(AbstractTimeStamped):
    day = models.DateField(null=True)
    reservation = models.ForeignKey(
        "reservations.Reservation",
        related_name="my_booked_days",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.day)


# Create your models here.
class Reservation(AbstractTimeStamped):
    """ Reservation model definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"
    STATUS_CHOICE = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )
    status = models.CharField(
        max_length=12, choices=STATUS_CHOICE, default=STATUS_PENDING
    )

    checkin_date = models.DateField(null=True)
    checkout_date = models.DateField(null=True)

    # foreign key
    guest = models.ForeignKey(
        "users.User", related_name="my_reservations", on_delete=models.CASCADE
    )
    room = models.ForeignKey(
        "rooms.Room", related_name="my_reservations", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"Room: {self.room} reservation on {self.checkin_date}"

    def is_in_progress(self):
        today = timezone.now().date()
        return (today >= self.checkin_date) and (today <= self.checkout_date)

    is_in_progress.short_description = "progress?"
    is_in_progress.boolean = True

    def is_finished(self):
        today = timezone.now().date()
        return today > self.checkout_date

    is_finished.short_description = "finished?"
    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.checkin_date
            end = self.checkout_date
            difference = end - start

            is_reservated = BookedDay.objects.filter(
                Q(day__range=(start, end)) & Q(reservation=self)
            ).exists()
            print(is_reservated)
            if is_reservated is False:
                super().save(*args, **kwargs)
                for i in range(difference.days + 1):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)

        else:
            return super().save(*args, **kwargs)

reservations/views.py
import datetime
from django.shortcuts import render
from django.shortcuts import redirect, reverse
from .models import BookedDay, Reservation
from rooms.models import Room
from django.contrib import messages
from django.views.generic import View
from django.http import Http404
from django.contrib.auth.decorators import login_required

from reviews.forms import CreateReviewForm


class AlreadyReserved(Exception):
    pass


# Create your views here.
def create(request, room, year, month, day):
    try:
        reserved_date = datetime.datetime(year, month, day)
        room = Room.objects.get(pk=room)
        booked = BookedDay.objects.get(day=reserved_date, reservation__room=room)
        # booked need not to be exist for reservation.
        raise AlreadyReserved()
    except (Room.DoesNotExist, AlreadyReserved):
        messages.error(request, "Invalid access for making a reservation.")
        return redirect(reverse("core:home"))
    except BookedDay.DoesNotExist:
        reservation = Reservation.objects.create(
            checkin_date=reserved_date,
            checkout_date=reserved_date + datetime.timedelta(days=1),
            room=room,
            guest=request.user,
        )

        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


"""class ReservationDetailView(DetailView):
    model = Reservation"""


class ReservationDetailView(View):
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = Reservation.objects.get_or_none(pk=pk)
        review_form = CreateReviewForm()

        if reservation is None:
            raise Http404("Invalid access")

        if (
            reservation.guest != self.request.user
            and reservation.room.host != self.request.user
        ):
            raise Http404("Neither guest or host.")

        return render(
            self.request,
            "reservations/reservation_detail.html",
            {"object": reservation, "review_form": review_form},
        )


@login_required
def edit_reservation(request, pk, verb):
    print(pk, verb)

    reservation = Reservation.objects.get_or_none(pk=pk)

    if reservation is None:
        raise Http404("Invalid access")

    if reservation.guest != request.user and reservation.room.host != request.user:
        raise Http404("Neither guest or host.")

    if verb == "cancel":
        reservation.status = Reservation.STATUS_CANCELED
        BookedDay.objects.filter(reservation=reservation).delete()
    elif verb == "confirm":
        reservation.status = Reservation.STATUS_CONFIRMED

    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": pk}))

templates/reservations/reservation_detail.html
{% extends 'base.html' %} 
{% block pagename %} {{object.guest.first_name}}'s reservation{% endblock pagename %} 
{% block content %}

<div class ="container h-1/2 mx-auto my-10 flex flex-col border border-gray-300 rounded-lg">
    <div class="bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{object.room.first_image}})"></div>
    <div class="p-3 border-b">
        <span>{{object.checkin_date}} - {{object.checkout_date}}</span>
        <span class="ml-5 {% if object.status == 'pending' %} text-green-400 {% elif object.status == 'cancelled' %} text-red-400 {% else %} text-blue-400 {% endif %} font-bold">{{object.get_status_display}}
    </div>
    <div class="p-5 border-b text-lg">
        {{object.room.name}}
    </div>    
    <div class="w-full h-auto p-5 flex content-start border-b">
        <div class="w-12 h-12 mr-4">
            {% include "partials/avatar.html" with profile=object.room.host %}
            <p class="text-gray-600 font-light text-center text-xs">{{ object.room.host.first_name }}</p>
        </div>
        <div>
            <p>Contact your Airbnb Host</p>
            <a href="{% url 'conversations:go' object.room.host.pk object.guest.pk %}" class="text-green-400">Send a Message</a>
        </div>
    </div>
    <div class="w-full h-auto p-5 flex items-center">
        
        {% if objects.status != 'canceled' %}
        
            {% if object.status == 'confirmed' and object.is_finished %}
                <span class="text-2xl font-medium mx-auto mb-5">Write you review</span>
                <form method="POST" action="{% url 'reviews:create' object.room.pk %}" class="flex flex-col w-1/2 border rounded-lg p-5 mx-auto form-auth">
                    {% csrf_token %}
                    {{ review_form }}
                    <button class="btn mx-auto w-1/2 bg-red-500 hover:bg-red-600 text-white transition duration-150">Write Review</button>
                </form>
            {% else %}
        
                {% if object.status == 'pending' %}
                <a href="{% url 'reservations:edit' object.pk 'cancel' %}" class="btn w-1/5 bg-red-500 hover:bg-red-600 text-white transition duration-150">Cancel Reservation</a>
                    {% if object.room.host == user %}
                <a href="{% url 'reservations:edit' object.pk 'confirm' %}" class="ml-5 btn w-1/5 bg-red-500 hover:bg-red-600 text-white transition duration-150">Confirm Reservation</a>
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endif %}
            
            
    </div>
</div>

{% endblock content %}