config/urls.py
import os
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path(os.environ.get("DJANGO_ADIN", "admin/"), admin.site.urls),    
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from rooms import views as rooms_views

app_name = "core"

urlpatterns = [
    path("", rooms_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("<int:pk>/", views.UserDetailView.as_view(), name="user"),
    path("favorite/", views.FavoriteView.as_view(), name="favorite"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:user_id>/send_verify/",
         views.send_verify_view, name="send-verify"),
    # path("login", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("verify/<str:key>/", views.complete_verification, name="verify"),
    path("login/github/", views.github_login, name="github"),
    path("login/github/callback/", views.github_callback, name="github_callback"),
    path("login/kakao/", views.kakao_login, name="kakao"),
    path("login/kakao/callback", views.kakao_callback, name="kakao_callback"),
    path("start-host/", views.switch_host, name="switch_host"),
    path("switch-language/", views.switch_language, name="switch_lang"),
]

users/models.py
import uuid
import os

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from core.managers import CustomUserManager


# Create your models here.
class User(AbstractUser):
    """ Custom user model """

    GENDER_MALE = "Male"
    GENDER_FEMALE = "Female"
    GENDER_OTHER = "Other"

    GENDER_CHOICE = (
        (GENDER_MALE, _("Male")),
        (GENDER_FEMALE, _("Female")),
        (GENDER_OTHER, _("Other")),
    )

    LANG_KOR = "KR"
    LANG_ENG = "EN"
    LANG_CHOICE = ((LANG_KOR, _("Korean")), (LANG_ENG, _("English")))

    CURRENCY_USD = "USD"
    CURRENCY_KRW = "KRW"
    CURRENCY_CHOICE = ((CURRENCY_USD, _("US dollor")),
                       (CURRENCY_KRW, _("Korea Won")))

    LOGIN_METHOD_EMAIL = "EM"
    LOGIN_METHOD_GITHUB = "GH"
    LOGIN_METHOD_KAKAO = "KK"
    LOGIN_METHOD_CHOICE = (
        (LOGIN_METHOD_EMAIL, "Email"),
        (LOGIN_METHOD_GITHUB, "Github"),
        (LOGIN_METHOD_KAKAO, "Kakao"),
    )

    avatar = models.ImageField(_("avatar"), blank=True, upload_to="avatars")
    gender = models.CharField(
        _("gender"), choices=GENDER_CHOICE, max_length=10, blank=True)
    bio = models.TextField(_("bio"), blank=True, default="")
    birthday = models.DateField(_("birthday"), null=True, blank=True)
    language = models.CharField(_("language"),
                                choices=LANG_CHOICE, max_length=2, blank=True, default=LANG_KOR
                                )
    currency = models.CharField(_("currency"),
                                choices=CURRENCY_CHOICE, max_length=3, blank=True, default=CURRENCY_KRW
                                )
    is_superhost = models.BooleanField(_("is superhost"), default=False)
    email_verified = models.BooleanField(_("email verified"), default=False)
    email_secret = models.CharField(max_length=128, default="")
    login_method = models.CharField(
        max_length=2, choices=LOGIN_METHOD_CHOICE, default=LOGIN_METHOD_EMAIL
    )

    objects = CustomUserManager()

    def get_absolute_url(self):
        return reverse("users:user", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is True:
            pass
        else:
            self.email_secret = uuid.uuid4().hex[:20]
            self.save()
            # using template file instead.
            link = f"{os.environ.get('SITE_URL')}/users/verify/{self.email_secret}"
            html_msg = render_to_string(
                "mail_body.html", context={"link": link})
            # html_msg = f'<p>This is just verficiatino mail and do not reply.</p><p>To verify click <a href="http://127.0.0.1:8000/users/{self.email_secret}">here</a></p>'
            send_mail(
                _("Hello, from DjangoBnB, account verification mail!"),
                strip_tags(html_msg),
                "pleed0215@gmail.com",
                [self.email, ],
                fail_silently=False,
                html_message=html_msg,
            )

users/views.py
import os
import requests
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import UpdateView, TemplateView
from django.views.generic import FormView, DetailView
from django.contrib.auth import (
    authenticate,
    login,
    logout,
    views as auth_views,
    forms as auth_forms,
)

from django.http import Http404
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils import translation


from . import models, forms, mixins
from django import forms as django_forms

# switch language


class FavoriteView (TemplateView):
    template_name = "users/favorite.html"


def switch_language(request):
    lang = request.GET.get("lang", None)

    if lang is not None:
        request.session[translation.LANGUAGE_SESSION_KEY] = lang

    return HttpResponse(status=200)

# Create your views here.


class UserDetailView(DetailView):
    model = models.User
    context_object_name = "profile"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["hello"] = "Hello"
        return context


# Login Views
"""class LoginView(FormView):
    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")

        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            print("login success")
            login(self.request, user)
            return redirect(reverse("core:home"))
        else:
            print("login failed")
        return super().form_valid(form)"""


class LoginView(mixins.LoggedOutOnlyView, auth_views.LoginView):
    template_name = "users/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            if user.email_verified is True:
                print("login success")
                login(self.request, user)
                return super().form_valid(form)
            else:
                return render(
                    self.request,
                    "users/verification_not_yet.html",
                    context={"user_id": user.pk},
                )
        else:
            print("login failed")
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")


def send_verify_view(request, user_id):
    try:
        user = models.User.objects.get(pk=user_id)
        user.verify_email()
        return render(
            request,
            "users/sending_verification.html",
            context={"email": user.email, "user_id": user.pk},
        )
    except models.User.DoesNotExist:
        return redirect("404.html")


# edit profile view
# url - users:edit
class UpdateProfileView(mixins.LoginOnlyView, SuccessMessageMixin, UpdateView):
    fields = (
        "email",
        "first_name",
        "last_name",
        "avatar",
        "bio",
        "gender",
        "currency",
        "language",
    )
    model = models.User
    template_name = "users/update-profile.html"
    context_object_name = "profile"
    success_message = "Profile updated"

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = models.User.objects.get(pk=self.request.user.pk)
        email = form.cleaned_data.get("email")
        first_name = form.cleaned_data.get("first_name")
        last_name = form.cleaned_data.get("last_name")
        avatar = form.cleaned_data.get("avatar")
        bio = form.cleaned_data.get("bio")
        gender = form.cleaned_data.get("gender")
        currency = form.cleaned_data.get("currency")
        language = form.cleaned_data.get("language")

        if email != user.email:
            # email(username) changed.
            try:
                # check if username is unique.
                models.User.objects.get(username=email)
                messages.error(
                    self.request,
                    "The email address you wrote is already exist. Use another please.",
                )
                return redirect(reverse("users:update"))

            except models.User.DoesNotExist:
                # case of username is unique.
                # 문제 발생: super().form_valid를 사용하면 내가 저장한 데이터가 없어지고
                # super().form_save를 안 쓰자니..너무 번거롭네.
                messages.info(
                    self.request,
                    f"Logged out. Your login method is changed.\n"
                    f"We send a verification email to {email}. Please check your email for verification.",
                )
                logout(self.request)
                user.username = email
                user.email = email
                user.first_name = first_name
                user.last_name = last_name
                user.avatar = avatar
                user.bio = bio
                user.gender = gender
                user.currency = currency
                user.language = language
                user.email_verified = False
                user.login_method = models.User.LOGIN_METHOD_EMAIL
                user.save()
                user.verify_email()

                return redirect(reverse("core:home"))
        else:
            # except email, other things are changed.
            return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["email"].widget.attrs = {
            "placeholder": "Username",
            "autofocus": True,
        }
        form.fields["first_name"].widget.attrs = {"placeholder": "First name"}
        form.fields["last_name"].widget.attrs = {"placeholder": "Last name"}
        form.fields["bio"].widget.attrs = {
            "placeholder": "Write your profile message here"
        }
        return form


@login_required
def switch_host(request):
    #request.session.pop('is_hosting', True)
    try:
        del request.session['is_host']
    except KeyError:
        request.session['is_host'] = True
    finally:
        return redirect(reverse("core:home"))


# login form page, using just View Class.
"""class LoginView(View):
    def get(self, request):
        return render(request, "users/login.html", context={"forms": forms.LoginForm()})

    def post(self, request):
        form = forms.LoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")

            user = authenticate(request, username=email, password=password)
            if user is not None:
                print("login success")
                login(request, user)
                return redirect(reverse("core:home"))
            else:
                print("login failed")
        else:
            print("data validation error")
        print(form.cleaned_data)
        return render(request, "users/login.html", context={"form": form})"""


def logout_view(request):
    logout(request)
    messages.info(request, "Good bye!")
    return redirect(reverse("core:home"))


# Signup Views
class SignupView(FormView):
    template_name = "users/signup.html"
    form_class = forms.SignupForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")

        form.save()
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            return render(
                self.request,
                "users/sending_verification.html",
                context={"email": user.email, "user_id": user.pk},
            )
        else:
            return redirect(self.get_success_url())


def complete_verification(request, key):
    is_success = False
    print(key)
    try:
        user = models.User.objects.get(email_secret=key)
        if user is not None:
            user.email_verified = True
            user.save()
            is_success = True
        print("success")

    except models.User.DoesNotExist as e:
        print(e)
        is_success = False
        print("failed")

    finally:
        return render(
            request, "users/verification.html", context={"success": is_success}
        )


class UpdatePasswordView(mixins.EmailLoginOnlyView, auth_views.PasswordChangeView):
    template_name = "users/update-password.html"
    #    form_class = forms.UpdatePasswordForm

    def form_valid(self, form):
        # 이렇게 하는 대신에 get_success_url을 overriding 해도 된다.
        """self.success_url = reverse_lazy(
            "users:user", kwargs={"pk": self.request.user.pk}
        )"""
        messages.success(self.request, "Password updated")
        return super().form_valid(form)

    def get_success_url(self):
        return self.request.user.get_absolute_url()

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["old_password"].widget.attrs = {
            "placeholder": "Current password here.",
            "autofocus": True,
        }
        form.fields["new_password1"].widget.attrs = {
            "placeholder": "Write new password here"
        }
        form.fields["new_password2"].widget.attrs = {

templates/users/favorite.html
{% extends 'base.html' %} {% block pagename %} Favorite list
{% endblock pagename %} {% block content %}

{% if user.my_lists.count > 0 %}
<div class="w-full h-auto p-5 border rounded mt-5">
    <h3 class="text-lg text-gray-600 mb-4">{{user.first_name}}'s favorite list</h3>
    <div class="grid grid-cols-4 gap-4">
        {% for list in user.my_lists.all %}
            {% for r in list.rooms.all %}
                {% include "partials/room.html" with room=r %}
            {% endfor %}
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}

{% block pagename %}
    login
{% endblock pagename %}

{% block content %}
    <div class="xl:w-2/5 lg:w-2/5 md:w-40 sm:flex-shrink-0 border p-10 min-w-1/2 h-75vh overflow-y-auto">
        {% include "partials/social_login.html" %}        
        {% include "partials/form_auth.html" with form=form cta="Log in" %}
        <span class="font-medium text-gray-500">Don't you have account? <a class="text-blue-500 font-bold hover:underline" href="{% url 'users:signup' %}">Sign up</a> Now</span>
    </div>
{% endblock content %}
    

templates/users/sending_verification.html
{% extends 'base.html' %}
{% block pagename %}
Sending a verification mail to you~!
{% endblock pagename %}
{% block content %}
<h3 class="font-light text-gray-700">
We've send you a verification mail to {{email}}~!
Check your email and confirm your email address!
</h3>
<span>If you didn't get verification mail, click <a class="text-blue-500 hover:underline" href="{% url "users:send-verify" user_id %}">here</a> again.</span>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}

{% block pagename %}
    Sign up
{% endblock pagename %}

{% block content %}
    <div class="xl:w-2/5 lg:w-2/5 md:w-40 sm:flex-shrink-0 border p-10 min-w-1/2 h-75vh min-h-50vh overflow-y-auto">
        {% include "partials/social_login.html" %}
        {% include "partials/form_auth.html" with form=form cta="Sing up now" %}
        <span class="font-medium text-gray-500">Do you already have an account? <a class="text-blue-500 font-bold hover:underline" href="{% url 'users:login' %}">Log in</a> Now</span>
    </div>
{% endblock content %}
    

templates/users/update-password.html
{% extends 'base.html' %}
{% block pagename %}
Changing {{user.first_name}}'s password
{% endblock pagename %}

{% block content %}

{% ifequal user.login_method "EM" %}
<div class="xl:w-2/5 lg:w-2/5 md:w-40 sm:flex-shrink-0 border p-10 min-w-1/2 h-75vh overflow-y-auto">
    {% include "partials/form_auth.html" with form=form cta="Update Password" %}
</div>
{% else %}
<div class="xl:w-2/5 lg:w-2/5 md:w-40 sm:flex-shrink-0 border p-10 min-w-1/2 h-75vh overflow-y-auto">
    <p class="text-xl text-red-400 mx-auto">You logged in by using github or kakao authorization.</p>
    <p class="text-xl text-red-400 mx-auto">You cannot change password</p>

    <a class="w-1/6 mx-auto" href="{% url 'users:user' pk=user.pk %}">
        <div class="auth-btn bg-red-500 text-white text-center mx-auto">
            <p class="mx-auto">Back to profile</p>
        </div>
    </a>
</div>
{% endifequal %}


{% endblock content %}

templates/users/update-profile.html
{% extends 'base.html' %}
{% block pagename %}
update {{profile.first_name}}'s profile
{% endblock pagename %}

{% block content %}
<div class="xl:w-2/5 lg:w-2/5 md:w-40 sm:flex-shrink-0 border p-10 min-w-1/2 h-75vh overflow-y-auto">
    {% include "partials/form_auth.html" with form=form cta="Update Profile" %}
    <a class="text-teal-400 hover:underline mx-auto" href="{% url "users:password" %}">
        <p class="text-center">Change Password</p>
    </a>
</div>

{% endblock content %}

templates/users/user_detail.html
{% extends 'base.html' %} {% block pagename %} {{profile.first_name}}'s profile
{% endblock pagename %} {% block content %}
<div class="border p-10 w-1/2 h-50vh overflow-y-auto flex flex-col items-center">
    <div class="w-40 h-40">
        {% include 'partials/avatar.html' with profile=profile %}
    </div>
    <div class="flex justify-center items-center h-30 mt-3">
        <span class="text-2xl text-gray-700">{{profile.first_name}}</span>
        {% if profile.is_superhost %}
        <span class="ml-2"><i class="fas fa-check-circle fa-2x text-teal-400"></i></span>
        {% endif %}
    </div>
    <p class="text-xl text-gray-600 mt-3">
        {{profile.bio}}
    </p>
    {% if profile == user %}
    <div class="btn mt-6 text-center bg-red-600 w-4/5 hover:bg-red-500 transition-colors duration-300">
        <a class="text-white" href="{% url 'users:update' %}">Edit Profile</a>
    </div>
    {% endif %}
</div>
{% if profile.my_rooms.count > 0 %}
<div class="w-full h-auto p-5 border rounded mt-5">

    <h3 class="text-lg text-gray-600 mb-4">{{profile.first_name}}'s rooms</h3>
    <div class="grid grid-cols-4 gap-4">
        {% for r in profile.my_rooms.all %}
        {% include "partials/room.html" with room=r %}
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock content %}

templates/users/verification.html
{% extends 'base.html' %}
{% block pagename %}
Result of user verification
{% endblock pagename %}
{% block content %}
    {% if success %} 
    <h2>You have confirmed your account!</h2>
    <h3>Welcome to out site!</h3>
    {% else %}
    Error, invalid token!
    {% endif %}
{% endblock content %}

templates/users/verification_not_yet.html
{% extends 'base.html' %}
{% block pagename %}
Result of user verification
{% endblock pagename %}
{% block content %}
    <h1>Your email address is not confirmed!</h1>
    <h3>Please verify your email address and try to log in again</h3>
    <h5>Haven't you received verification email?? <a class="text-blue-500 font-bold hover:underline" href="{% url 'users:send-verify' user_id %}">Click here</a> if you want to get verification email again.</h5>
{% endblock content %}